on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Create packages
        run: go run main.go

      - name: Install
        run: sudo apt install -y reprepro

      - name: Build repo amd64
        run: reprepro -b repo includedeb plucky tmp/amd64/*.deb

      - name: Build repo amd64
        run: reprepro -b repo includedeb plucky tmp/arm64/*.deb

      - name: "Delete extra files"
        run: rm -rf repo/conf repo/db

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: repo

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # - name: Adding summary
      #   run: |
      #     echo ':rocket:' >> $GITHUB_STEP_SUMMARY
      #     echo '' >> $GITHUB_STEP_SUMMARY
      #     echo '```bash' >> $GITHUB_STEP_SUMMARY
      #     echo 'curl -sfLo /etc/apt.trusted.gpg.d/${{ needs.build.outputs.keyring }}.asc ${{ steps.deploy-pages.outputs.page_url }}gpg.key' >> $GITHUB_STEP_SUMMARY
      #     echo 'echo "deb ${{ steps.deploy-pages.outputs.page_url }} ${{ env.CODENAME }} ${{ env.COMPONENTS }}" >/etc/apt/sources.list.d/${{ env.REPO_NAME }}.list' >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY
